//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneFix.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permision()
        {
            this.Rolls = new HashSet<Roll>();
        }
    
        public int permisionID { get; set; }
        public Nullable<bool> viewClients { get; set; }
        public Nullable<bool> viewPhones { get; set; }
        public Nullable<bool> viewService { get; set; }
        public Nullable<bool> viewRepair { get; set; }
        public Nullable<bool> addClient { get; set; }
        public Nullable<bool> addPhones { get; set; }
        public Nullable<bool> addService { get; set; }
        public Nullable<bool> addRepair { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roll> Rolls { get; set; }
    }
}
