//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneFix.DAL
{
    
    public partial class Phone
    {
        public int phoneID { get; set; }
        public int clientID { get; set; }
        public string IMEI { get; set; }
        public string brand { get; set; }
        public string type { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
