//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneFix.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceSheet()
        {
            this.RepairSheets = new HashSet<RepairSheet>();
        }
    
        public int ID_Service { get; set; }
        public int clientID { get; set; }
        public string claimed_defect { get; set; }
        public string phone_description_on_reception { get; set; }
        public string accesories { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairSheet> RepairSheets { get; set; }
    }
}
