//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneFix.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workmanship
    {
        public int workmanshipID { get; set; }
        public decimal time { get; set; }
        public decimal price { get; set; }
        public string operations { get; set; }
        public int partsID { get; set; }
        public int repairID { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual RepairSheet RepairSheet { get; set; }
    }
}
