//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneFix.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workmanship
    {
        public int workmanshipID { get; set; }
        public Nullable<decimal> time { get; set; }
        public Nullable<decimal> price { get; set; }
        public string operations { get; set; }
        public int ID_repair { get; set; }
    
        public virtual RepairSheet RepairSheet { get; set; }
    }
}
